---
name: "run py script"
# on:
#   schedule:
#     - cron: '*/5 * * * *'
on: workflow_dispatch

jobs:
  hello:
    name: "Say hello"
    runs-on: ubuntu-latest
    steps:        
      - name: clone repo
        uses: actions/checkout@v3 
        
      - name: pyversion
        run : python --version
        
      - name: config git
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: run py script
        run: python art.py
